# .github/workflows/verify-signed-commits.yml
name: Verify Signed Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-signatures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history so git log works

      - name: Check for signed commits
        run: |
          echo " Checking for signed commits in PR..."
          COMMITS=$(git log --pretty=format:'%G?' ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          echo "$COMMITS" | grep -v 'G' && {
            echo " Unsigned commits detected.";
            exit 1;
          } || echo " All commits are signed.";
